### ISSUE TITLE
Does not work on MacOS Mohave

### ISSUE THREAD

**Issue by cocoCakes** [psyk27/nas-photogenerator#1]
### Issue:
`pip install -r requirements.txt`
ERROR: No matching distribution found for pywin32==303

I don't believe any Mac or Linux OS supports pywin32. I've forked this and will work on it for Mac. Will probably require separating script into OS compatible script that includes then includes OS specific scripts depending on OS

### Environment:
$ python --version
Python 3.9.7

**Comment by daih27** [comment]
I uploaded a MacOS script, although it was tested on an M1 Mac. Test it and let me know what changes need to be made if any.

**Comment by cocoCakes** [comment]
Commit https://github.com/psyk27/nas-streamproof-generator/commit/ed90fc30675d6a0177477018204d2c605f2808e1 does fix the pip installation problem so will close this issue. Afterwards encountered a race condition and will open new issue.
